In [13]:
import pandas as pd
archivo_excel = 'C:/Users/esteb/OneDrive/Documents/Maestria/I/Programacion/Trabajos/I/Repositorio/Datos.xlsx'
datos = pd.read_excel(archivo_excel)
datos.head()
datos.describe()

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o
count,9.000000,9.000000,9.000000,9.000000e+00,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,100.000000,130.000000,0.277778,2.014167e-04,0.132422,1.620556,2.672222,3.508556,2.624556,0.024210,0.006771,1.250222,1.872222,2.308667,2.127000
std,54.772256,27.386128,0.151993,3.244205e-04,0.122094,0.101076,0.275126,0.412794,1.251375,0.032375,0.004128,0.115118,0.177414,0.266092,1.034483
min,20.000000,90.000000,0.056000,1.000000e-08,0.003800,1.436000,2.200000,2.800000,0.601000,0.000060,0.001370,1.045000,1.575000,1.863000,0.480000
25%,60.000000,110.000000,0.167000,2.700000e-06,0.034800,1.565000,2.500000,3.250000,1.763000,0.001060,0.003870,1.178000,1.750000,2.125000,1.411000
50%,100.000000,130.000000,0.278000,4.000000e-05,0.099000,1.646000,2.725000,3.588000,2.790000,0.009100,0.006400,1.275000,1.900000,2.350000,2.237000
75%,140.000000,150.000000,0.389000,2.300000e-04,0.204800,1.702000,2.900000,3.850000,3.623000,0.033270,0.008880,1.347000,2.025000,2.538000,2.932000
max,180.000000,170.000000,0.500000,9.600000e-04,0.353100,1.725000,2.975000,3.963000,4.181000,0.092990,0.014460,1.374000,2.075000,2.613000,3.456000

In [19]:
#La tabla de datos se subio con la siguiente nomenclatura; 
from PIL import Image
ruta_imagen = ruta_imagen = r"C:\Users\esteb\OneDrive\Documents\Maestria\I\Programacion\Trabajos\I\Repositorio\Imagen tabla.png"
imagen_tabla = Image.open(ruta_imagen)
imagen_tabla.show()